name: Deploy to Amazon ECS

on:
  push:
    branches: ['master']

env:
  CONTAINER_NAME: medical-supplier-manager
  CONTAINER_TAG: latest

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v3

      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build docker image
        env:
          VITE_INTERVIEW_API_URL: ${{ secrets.VITE_INTERVIEW_API_URL }}
        run: docker build -t ${{ env.CONTAINER_NAME }} .

      - name: Tag image
        run: docker tag ${{ env.CONTAINER_NAME }} ${{ secrets.DOCKER_USERNAME }}/${{ env.CONTAINER_NAME }}:${{ env.CONTAINER_TAG }}

      - name: Publish image to docker hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.CONTAINER_NAME }}:${{ env.CONTAINER_TAG }}

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: SSH Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: 22
          script: |
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/${{ env.CONTAINER_NAME }}
            sudo docker stop ${{ secrets.DOCKER_USERNAME }}/${{ env.CONTAINER_NAME }}
            sudo docker rm ${{ secrets.DOCKER_USERNAME }}/${{ env.CONTAINER_NAME }}
            sudo docker run -d -p 80:80 ${{ secrets.DOCKER_USERNAME }}/${{ env.CONTAINER_NAME }}
